### ISSUE TITLE
config里面的ftp服务器的地址是某台电脑的公网ip地址吗

### ISSUE THREAD

**Issue by Z020912DY** [HammerCloth/tiktok#14]

**Comment by HammerCloth** [comment]
是的

**Comment by Z020912DY** [comment]
> 是的

需要使用到内网穿透的花生壳吗？你们的电脑的公网ip是怎么得到的呀？没想到能得到回复，谢谢up！！

**Comment by HammerCloth** [comment]
> > 是的
> 
> 需要使用到内网穿透的花生壳吗？你们的电脑的公网ip是怎么得到的呀？没想到能得到回复，谢谢up！！

网上的云服务器就有公网ip
