### ISSUE TITLE
您好，我想请问一个关于视频播放的问题。

### ISSUE THREAD

**Issue by LittleGrey-John** [HammerCloth/tiktok#16]
您好，在视频设计模块的文档中，我注意到参考文献里面有nginx服务器的相关信息，我想知道为什么需要nginx服务器，如果直接把视频文件存在本地，然后返回play_url的时候，内容是自己主机的ip address+filepath，这样能实现在客户端上播放视频的功能吗？谢谢了

**Comment by HammerCloth** [comment]
不能，实现播放视频需要通过http协议，我使用nginx作为http容器，通过http协议实现视频文件传输
| |
司一雄
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Jiahan ***@***.***> |
| 发送日期 | 2023年02月15日 18:22 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [HammerCloth/tiktok] 您好，我想请问一个关于视频播放的问题。 (Issue #16) |

您好，在视频设计模块的文档中，我注意到参考文献里面有nginx服务器的相关信息，我想知道为什么需要nginx服务器，如果直接把视频文件存在本地，然后返回play_url的时候，内容是自己主机的ip address+filepath，这样能实现在客户端上播放视频的功能吗？谢谢了
